TodoList\Domain\ClientModel\TodoList\Task:
  type: entity
  table: todolist_task

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    description:
      type: text
    status:
      type: string
